//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditPrograms
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> LoanTerm { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> DownPayment { get; set; }
        public Nullable<decimal> MonthlyPayment { get; set; }
        public Nullable<bool> LifeInsurance { get; set; }
    }
}
