//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MortgageCalculatorEntities : DbContext
    {
        public MortgageCalculatorEntities()
            : base("name=MortgageCalculatorEntities")
        {
        }
        private static MortgageCalculatorEntities _context;

        public static MortgageCalculatorEntities GetContext()
        {
            if (_context == null)
                _context = new MortgageCalculatorEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CreditPrograms> CreditPrograms { get; set; }
        public virtual DbSet<PropertiesPage> Properties { get; set; }
        public virtual DbSet<regist> regist { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
